prev_packages:
  - docker.io
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc
  - docker-ce
  - docker-ce-cli
  - containerd.io 
  - docker-buildx-plugin 
  - docker-compose-plugin
  - docker-ce-rootless-extras
  
docker_apt_repo: "deb [arch={{ ansible_architecture | default('amd64') }}] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"

prev_files:
  - /etc/apt/sources.list.d/docker.list
  - /etc/apt/keyrings/docker.asc
  - /var/lib/containerd
  - /var/lib/docker

required_packages:
  - ca-certificates
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin