apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-server-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: echo-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
